services:
  - type: web
    name: ecg-1d-cnn
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --timeout 180
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
